<a href="https://colab.research.google.com/github/sanaaranjith/SCMS_practical_class/blob/main/Day2_practise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
data = "/content/employees.csv"

In [3]:
df = pd.read_csv(data ,dtype={'EMPLOYEE_ID':str,'MANAGER_ID':str})

FileNotFoundError: [Errno 2] No such file or directory: '/content/employees.csv'

In [4]:
from google.colab import files
files.upload()

Saving employees.csv to employees.csv

{'employees.csv': b'EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID\n198,Donald,OConnell,DOCONNEL,650.507.9833,21-JUN-07,SH_CLERK,2600, - ,124,50\n199,Douglas,Grant,DGRANT,650.507.9844,13-JAN-08,SH_CLERK,2600, - ,124,50\n200,Jennifer,Whalen,JWHALEN,515.123.4444,17-SEP-03,AD_ASST,4400, - ,101,10\n201,Michael,Hartstein,MHARTSTE,515.123.5555,17-FEB-04,MK_MAN,13000, - ,100,20\n202,Pat,Fay,PFAY,603.123.6666,17-AUG-05,MK_REP,6000, - ,201,20\n203,Susan,Mavris,SMAVRIS,515.123.7777,07-JUN-02,HR_REP,6500, - ,101,40\n204,Hermann,Baer,HBAER,515.123.8888,07-JUN-02,PR_REP,10000, - ,101,70\n205,Shelley,Higgins,SHIGGINS,515.123.8080,07-JUN-02,AC_MGR,12008, - ,101,110\n206,William,Gietz,WGIETZ,515.123.8181,07-JUN-02,AC_ACCOUNT,8300, - ,205,110\n100,Steven,King,SKING,515.123.4567,17-JUN-03,AD_PRES,24000, - , - ,90\n101,Neena,Kochhar,NKOCHHAR,515.123.4568,21-SEP-05,AD_VP,17000, - ,100,90\n102,Lex,De Haan,LDEHAAN,515.123.4569,13-JAN-01,AD_VP,17000, - ,100,90\n103,Alexander,Hunold,AHUNOLD,590.423.4567,03-JAN-06,IT_PROG,9000, - ,102,60\n104,Bruce,Ernst,BERNST,590.423.4568,21-MAY-07,IT_PROG,6000, - ,103,60\n105,David,Austin,DAUSTIN,590.423.4569,25-JUN-05,IT_PROG,4800, - ,103,60\n106,Valli,Pataballa,VPATABAL,590.423.4560,05-FEB-06,IT_PROG,4800, - ,103,60\n107,Diana,Lorentz,DLORENTZ,590.423.5567,07-FEB-07,IT_PROG,4200, - ,103,60\n108,Nancy,Greenberg,NGREENBE,515.124.4569,17-AUG-02,FI_MGR,12008, - ,101,100\n109,Daniel,Faviet,DFAVIET,515.124.4169,16-AUG-02,FI_ACCOUNT,9000, - ,108,100\n110,John,Chen,JCHEN,515.124.4269,28-SEP-05,FI_ACCOUNT,8200, - ,108,100\n111,Ismael,Sciarra,ISCIARRA,515.124.4369,30-SEP-05,FI_ACCOUNT,7700, - ,108,100\n112,Jose Manuel,Urman,JMURMAN,515.124.4469,07-MAR-06,FI_ACCOUNT,7800, - ,108,100\n113,Luis,Popp,LPOPP,515.124.4567,07-DEC-07,FI_ACCOUNT,6900, - ,108,100\n114,Den,Raphaely,DRAPHEAL,515.127.4561,07-DEC-02,PU_MAN,11000, - ,100,30\n115,Alexander,Khoo,AKHOO,515.127.4562,18-MAY-03,PU_CLERK,3100, - ,114,30\n116,Shelli,Baida,SBAIDA,515.127.4563,24-DEC-05,PU_CLERK,2900, - ,114,30\n117,Sigal,Tobias,STOBIAS,515.127.4564,24-JUL-05,PU_CLERK,2800, - ,114,30\n118,Guy,Himuro,GHIMURO,515.127.4565,15-NOV-06,PU_CLERK,2600, - ,114,30\n119,Karen,Colmenares,KCOLMENA,515.127.4566,10-AUG-07,PU_CLERK,2500, - ,114,30\n120,Matthew,Weiss,MWEISS,650.123.1234,18-JUL-04,ST_MAN,8000, - ,100,50\n121,Adam,Fripp,AFRIPP,650.123.2234,10-APR-05,ST_MAN,8200, - ,100,50\n122,Payam,Kaufling,PKAUFLIN,650.123.3234,01-MAY-03,ST_MAN,7900, - ,100,50\n123,Shanta,Vollman,SVOLLMAN,650.123.4234,10-OCT-05,ST_MAN,6500, - ,100,50\n124,Kevin,Mourgos,KMOURGOS,650.123.5234,16-NOV-07,ST_MAN,5800, - ,100,50\n125,Julia,Nayer,JNAYER,650.124.1214,16-JUL-05,ST_CLERK,3200, - ,120,50\n126,Irene,Mikkilineni,IMIKKILI,650.124.1224,28-SEP-06,ST_CLERK,2700, - ,120,50\n127,James,Landry,JLANDRY,650.124.1334,14-JAN-07,ST_CLERK,2400, - ,120,50\n128,Steven,Markle,SMARKLE,650.124.1434,08-MAR-08,ST_CLERK,2200, - ,120,50\n129,Laura,Bissot,LBISSOT,650.124.5234,20-AUG-05,ST_CLERK,3300, - ,121,50\n130,Mozhe,Atkinson,MATKINSO,650.124.6234,30-OCT-05,ST_CLERK,2800, - ,121,50\n131,James,Marlow,JAMRLOW,650.124.7234,16-FEB-05,ST_CLERK,2500, - ,121,50\n132,TJ,Olson,TJOLSON,650.124.8234,10-APR-07,ST_CLERK,2100, - ,121,50\n133,Jason,Mallin,JMALLIN,650.127.1934,14-JUN-04,ST_CLERK,3300, - ,122,50\n134,Michael,Rogers,MROGERS,650.127.1834,26-AUG-06,ST_CLERK,2900, - ,122,50\n135,Ki,Gee,KGEE,650.127.1734,12-DEC-07,ST_CLERK,2400, - ,122,50\n136,Hazel,Philtanker,HPHILTAN,650.127.1634,06-FEB-08,ST_CLERK,2200, - ,122,50\n137,Renske,Ladwig,RLADWIG,650.121.1234,14-JUL-03,ST_CLERK,3600, - ,123,50\n138,Stephen,Stiles,SSTILES,650.121.2034,26-OCT-05,ST_CLERK,3200, - ,123,50\n139,John,Seo,JSEO,650.121.2019,12-FEB-06,ST_CLERK,2700, - ,123,50\n140,Joshua,Patel,JPATEL,650.121.1834,06-APR-06,ST_CLERK,2500, - ,123,50\n'}

In [5]:
df = pd.read_csv(data ,dtype={'EMPLOYEE_ID':str,'MANAGER_ID':str})

In [6]:
df['Salary_ranking'] = df['SALARY'].rank(method='dense',ascending=False)

In [7]:
max(df['SALARY'])

24000

In [8]:
df[df['EMPLOYEE_ID']==101]

Empty DataFrame
Columns: [EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID, Salary_ranking]
Index: []

In [9]:
# second highest salary

In [10]:
df.loc[df['Salary_ranking']==2,'SALARY']

10    17000
11    17000
Name: SALARY, dtype: int64

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   EMPLOYEE_ID     50 non-null     object
 1   FIRST_NAME      50 non-null     object
 2   LAST_NAME       50 non-null     object
 3   EMAIL           50 non-null     object
 4   PHONE_NUMBER    50 non-null     object
 5   HIRE_DATE       50 non-null     object
 6   JOB_ID          50 non-null     object
 7   SALARY          50 non-null     int64
 8   COMMISSION_PCT  50 non-null     object
 9   MANAGER_ID      50 non-null     object
 10  DEPARTMENT_ID   50 non-null     int64
 11  Salary_ranking  50 non-null     float64
dtypes: float64(1), int64(2), object(9)
memory usage: 4.8+ KB

In [12]:
df = df.merge(df,left_on='MANAGER_ID',right_on='EMPLOYEE_ID',suffixes=('','_manager'))
df["manager_name"] = df["FIRST_NAME"] + " " + df["LAST_NAME"]
df.columns

Index(['EMPLOYEE_ID', 'FIRST_NAME', 'LAST_NAME', 'EMAIL', 'PHONE_NUMBER',
       'HIRE_DATE', 'JOB_ID', 'SALARY', 'COMMISSION_PCT', 'MANAGER_ID',
       'DEPARTMENT_ID', 'Salary_ranking', 'EMPLOYEE_ID_manager',
       'FIRST_NAME_manager', 'LAST_NAME_manager', 'EMAIL_manager',
       'PHONE_NUMBER_manager', 'HIRE_DATE_manager', 'JOB_ID_manager',
       'SALARY_manager', 'COMMISSION_PCT_manager', 'MANAGER_ID_manager',
       'DEPARTMENT_ID_manager', 'Salary_ranking_manager', 'manager_name'],
      dtype='object')

In [14]:
df = df.sort_values(by='EMPLOYEE_ID',ascending=True)

In [16]:
df[['EMPLOYEE_ID','FIRST_NAME','MANAGER_ID_manager']]

   EMPLOYEE_ID   FIRST_NAME MANAGER_ID_manager
9          101        Neena                 -
10         102          Lex                 -
11         103    Alexander                100
12         104        Bruce                102
13         105        David                102
14         106        Valli                102
15         107        Diana                102
16         108        Nancy                100
17         109       Daniel                101
18         110         John                101
19         111       Ismael                101
20         112  Jose Manuel                101
21         113         Luis                101
22         114          Den                 -
23         115    Alexander                100
24         116       Shelli                100
25         117        Sigal                100
26         118          Guy                100
27         119        Karen                100
28         120      Matthew                 -
29         121         Adam                 -
30         122        Payam                 -
31         123       Shanta                 -
32         124        Kevin                 -
33         125        Julia                100
34         126        Irene                100
35         127        James                100
36         128       Steven                100
37         129        Laura                100
38         130        Mozhe                100
39         131        James                100
40         132           TJ                100
41         133        Jason                100
42         134      Michael                100
43         135           Ki                100
44         136        Hazel                100
45         137       Renske                100
46         138      Stephen                100
47         139         John                100
48         140       Joshua                100
0          198       Donald                100
1          199      Douglas                100
2          200     Jennifer                100
3          201      Michael                 -
4          202          Pat                100
5          203        Susan                100
6          204      Hermann                100
7          205      Shelley                100
8          206      William                101